include:
  - project: 'common/gitlab-ci'
    ref: v0.4.15
    file: '/templates/npm-package.yml'

e2e_test:
  stage: test
  image: registry.kyso.io/docker/node-builder:16.15.1-alpine3.16
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - node -v
    - npm -v
    - ls
    - docker-compose up -f ./test/docker-compose.yml &
    - sleep 120
    - npm run test
    