image: node:12.13.0

stages:
  - deploy 

deploy-to-private-registry:
  stage: deploy 
  script:
    - npm config set @kyso-io:registry https://gitlab.kyso.io/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    - npm config set https://gitlab.kyso.io/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:authToken=${CI_JOB_TOKEN}
    - npm publish