include:
  - project: 'common/gitlab-ci'
    ref: v0.4.15
    file: '/templates/npm-package.yml'

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

e2e_test:
  stage: test
  image: registry.kyso.io/docker/node-builder:16.15.1-alpine3.16
  before_script:
    - !reference [.npm-config, before_script]
  services:
    - docker:dind
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d -f ./test/docker-compose.yml
    - npm install
    - npm run test
    