include:
  - project: 'common/gitlab-ci'
    ref: v0.4.21
    file:
    - '/includes/docker-config.yml'
    - '/templates/npm-package.yml'

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_VERSION: 20.10.17
  


e2e_test:
  allow_failure: true
  stage: test
  image: registry.kyso.io/docker/node-docker-builder:16.16.0-bullseye-slim
  services:
    - name: registry.kyso.io/docker/docker:${DOCKER_VERSION}-dind-original
      alias: docker
  variables:
    ACCESS_TOKEN_AUTOMATIC_TESTING: $ACCESS_TOKEN_AUTOMATIC_TESTING
    ACCESS_TOKEN_AUTOMATIC_TESTING_USERNAME: $ACCESS_TOKEN_AUTOMATIC_TESTING_USERNAME
  before_script:
    - !reference [.docker-config, before_script]
    - !reference [.npm-config, before_script]
  script:
    - sh test/ci_run_test docker
    - TITLE="Kyso Store Automatic Test Results "`date '+%F_%H:%M:%S'`
    - echo "Uploading report to Kyso.io"
    - npx kyso login --provider kyso --kysoInstallUrl https://kyso.io --username $ACCESS_TOKEN_AUTOMATIC_TESTING_USERNAME --token $ACCESS_TOKEN_AUTOMATIC_TESTING
    - sed -i 's/#TITLE/'"$TITLE"'/g' template-kyso.yaml
    - cp template-kyso.yaml ./test-results/kyso.yaml
    - npx kyso push --path ./test-results