include:
  - project: 'common/gitlab-ci'
    ref: v0.4.15
    file: '/templates/npm-package.yml'

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

e2e_test:
  stage: test
  image: registry.kyso.io/docker/node-builder:16.15.1-alpine3.16
  before_script:
    - !reference [.npm-config, before_script]
  services:
    - name: mongo:latest
      alias: mongo-test
      variables:
        MONGO_INITDB_ROOT_USERNAME: kadmin
        MONGO_INITDB_ROOT_PASSWORD: ksecret
    - name: registry.kyso.io/kyso-io/kyso-api/develop:latest
      alias: kyso-api-test
  
  script:
    - npm install
    - npm run test