include:
  - project: 'common/gitlab-ci'
    ref: v0.4.15
    file: '/templates/npm-package.yml'

e2e_test:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  before_script:
    - apt-get update -y
  script:
    - curl -sL https://deb.nodesource.com/setup_16.x | bash
    - apt-get install nodejs -yq
    - node -v
    - npm -v
    - docker-compose up&
    - sleep 60
    