image: node:16.13.2

stages:
  - deploy 

deploy-to-private-registry:
  stage: deploy 
  script:
    - npm config set @kyso-io:registry https://gitlab.kyso.io/api/v4/npm/
    - npm config set //gitlab.kyso.io/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - npm config set //gitlab.kyso.io/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
    - yarn install
    - yarn run prepare
    - yarn publish
