include:
  - project: 'common/gitlab-ci'
    ref: v0.4.21
    file:
    - '/includes/docker-config.yml'
    - '/templates/npm-package.yml'

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_VERSION: 20.10.17

e2e_test:
  allow_failure: true
  stage: test
  image: registry.kyso.io/docker/node-docker-builder:16.16.0-bullseye-slim
  services:
    - name: registry.kyso.io/docker/docker:${DOCKER_VERSION}-dind-original
      alias: docker
  before_script:
    - !reference [.docker-config, before_script]
    - !reference [.npm-config, before_script]
  script:
    - sh test/ci_run_test docker
    - npx kyso login --provider kyso --kysoInstallUrl https://kyso.io --username francisco@kyso.io --token d8a80fb2-02c4-4548-b371-ad94c1307289
    - echo "{"
    - npx push --path ./test-results