include:
  - project: 'common/gitlab-ci'
    ref: v0.4.15
    file: '/templates/npm-package.yml'

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

e2e_test:
  allow_failure: true
  stage: test
  image: registry.kyso.io/docker/node-docker-builder:16.16.0-bullseye-slim
  before_script:
    - !reference [.npm-config, before_script]
  services:
    - docker:dind
    - name: mongo:latest
      alias: mongo-test
      variables:
        MONGO_INITDB_ROOT_USERNAME: kadmin
        MONGO_INITDB_ROOT_PASSWORD: ksecret
  
  script:
    - export STORE_ENV_PATH=$PWD/test/.env
    - echo $STORE_ENV_PATH
    - docker version
    - docker login registry.kyso.io --username francisco --password CGyUeERRzr_f9hze_Qr2
    - docker run -v $STORE_ENV_PATH:/secrets/kyso-api/env -p 4000:4000 -e DOTENV_FILE=/secrets/kyso-api/env --network=host registry.kyso.io/kyso-io/kyso-api/develop:latest &
    - sleep 60
    - npm install
    - KYSO_API=http://localhost:4000/api/v1 npm run test