include:
  - project: 'common/gitlab-ci'
    ref: v0.4.21
    file:
    - '/includes/docker-config.yml'
    - '/templates/npm-package.yml'

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

e2e_test:
  allow_failure: true
  stage: test
  image: registry.kyso.io/docker/node-docker-builder:16.16.0-bullseye-slim
  before_script:
    - !reference [.docker-config, before_script]
    - !reference [.npm-config, before_script]
  services:
    - docker:dind
  script:
    - sh test/ci_run_test
